Get more creative

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,10 +1,62 @@
-#!/bin/sh
+#!/bin/bash
 
-indent() {
-  sed -u 's/^/       /'
-}
+APP_DIR="$1"
+ENV_DIR="$3"
 
-echo "-----> Found a .gitmodules-hack"
+# load required environment variables
+GIT_REPO_URL=$(<"$ENV_DIR/GIT_REPO_URL")
+GIT_SSH_KEY=$(<"$ENV_DIR/GIT_SSH_KEY")
 
-echo "Moving .gitmodules-hack to .gitmodules" | indent
-mv $1/.gitmodules-hack $1/.gitmodules
+if [[ -z $GIT_REPO_URL ]]; then
+    echo "Did you forget to set GIT_REPO_URL?"
+    exit 1
+fi
+
+if [[ -z $GIT_SSH_KEY ]]; then
+    echo "Did you forget to set GIT_SSH_KEY?"
+    exit 1
+fi
+
+# make sure we're in the root of the app dir
+cd "$APP_DIR"
+
+# remove existing .gitmodules-hack, we'll check out it again
+rm .gitmodules-hack
+
+# create an empty repo to fetch into
+git init -q
+
+# enable sparse checkouts, this will avoid checking out
+# all the files in the repo, we'll only check out .gitmodules
+git config core.sparseCheckout true
+echo ".gitmodules-hack" > .git/info/sparse-checkout
+
+# add the repo as a remote and fetch the repo's history
+git remote add origin "$GIT_REPO_URL"
+
+# install the ssh key
+mkdir -p ~/.ssh
+ssh-keyscan -H github.com >> ~/.ssh/known_hosts 2> /dev/null
+cp "$ENV_DIR/GIT_SSH_KEY" ~/.ssh/id_rsa
+echo >> ~/.ssh/id_rsa
+chmod 600 ~/.ssh/id_rsa
+
+# ignore/hide ssh warnings
+echo "Host *" >> ~/.ssh/config
+echo "   StrictHostKeyChecking no" >> ~/.ssh/config
+echo "   UserKnownHostsFile /dev/null" >> ~/.ssh/config
+echo "   LogLevel ERROR" >> ~/.ssh/config
+echo "-----> Installed SSH key from GIT_SSH_KEY"
+
+# checkout the revision that's being deployed
+git fetch -q --depth 1 origin -a > /dev/null
+git checkout -q ${SOURCE_VERSION:-master} > /dev/null
+echo "-----> Fetched shallow history from $GIT_REPO_URL"
+
+mv .gitmodules-hack .gitmodules
+echo "-----> Moved .gitmodules-hack to .gitmodules"
+
+# initialize all the submodules
+git submodule -q update --init --recursive
+echo "-----> Checked out all submodules"
+git submodule status | sed 's/^/       * /'
